### ISSUE TITLE
RuntimeError: signers not verified

### ISSUE THREAD

**Issue by kichinosukey** [beyond-blockchain/examples#20]
I added below code to "api/body.py"

```python
@api.route('/new-keypair', methods=['POST'])
def replace_keypair():

    name = request.json.get("name")
    user = g.store.read_user(name, 'user_table')

    keypair_old = user.keypair

    keypair = bbclib.KeyPair()
    keypair.generate()

    g.idPubkeyMap = id_lib.BBcIdPublickeyMap(domain_id)
    g.idPubkeyMap.update(user.user_id, public_keys_to_replace=[keypair.public_key], keypair=keypair_old)
    
    user.keypair = keypair

    return None
```

Then I run command below.

```shell
curl -X POST -H "Content-Type:application/json" localhost:5000/api/new-keypair -d '{"name":"test01"}'
```

But the response was "RuntimeError: signers not verified". I already has setup currency and user based on [this post](https://kichinosukey.hatenadiary.jp/entry/2019/11/06/000515).
Why this error occurred?

**Comment by ks91** [comment]
Thank you for trying to implement /api/new-keypair. Your code is helpful.

I am not sure why it caused the runtime error, but I noticed that your code does not update the user database, so if the API is called multiple times, it would try to sign the transaction with old private key, resulting in 'signers not verified'. Please see the implementation (I changed the interface according to our REST API design principle) I have just merged.

I forgot to add you in AUTHORS of payment-web, but I have done it locally, so that it will be included in the next update.

**Comment by kichinosukey** [comment]
Thank you for your reply. I updated the code and checked your implementation. I understood the cause of my mistake. Thank you!!
